version: '3'

services:
  db:
    # Temporarily define platform to run on Apple Silicon
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gpus
      MYSQL_USER: scraper
      MYSQL_PASSWORD: scraper
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
  scraper:
    build: ./scraper

volumes:
  db-volume:
